In [37]:
import numpy as np

In [38]:
test_list = [1, 2, 3, 4]

Often in research, you want to do the same operations on many data points at one time. A common way to store these data would be in a list.

If you wanted to multiply all the values in the list, however, it wouldn't work. Multiplying a list will just repeat the list a number of times.

In [39]:
print(test_list)
print(test_list * 2)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


This is where arrays come in. There are many advantages to using numpy arrays instead of lists. We will start with math operations.

One way to create an array is to turn a list into an array.

In [40]:
list2array = np.asarray(test_list)
print(list2array)
print(list2array * 2)

[1 2 3 4]
[2 4 6 8]


We can also create an array of random values.

In [41]:
random_array = np.random.rand(1, 4)
print(random_array)

[[0.53234195 0.43936962 0.25587093 0.7740053 ]]


In [42]:
rand_arr2 = np.random.randint(0,3,4)
print(rand_arr2)

[2 0 1 1]


np.randint goes from the lower value to one before the higher value. Using the example given above, you can get values from 0 (the lower value) to 2 (one before the higher value, 3). This is a bit confusing, but it is consistent with how python uses indices. Python is a 0-indexed language.

In [43]:
print(list2array)
print(list2array[0])
print(list2array[1])
print(list2array[2])
print(list2array[3])

[1 2 3 4]
1
2
3
4


In [44]:
#print(list2array[4])

In [45]:
print(list2array[0:2])
print(list2array[:2])

[1 2]
[1 2]


Even though 4 is not an index of the array, it reads it as a higher bound. Like np.random.randint, it considers the integer before the input number. So even though it doesn't make a lot of sense, there is an internal logic to it.

You can also just say to take from a value to the end by using a ":" with no number after.

In [46]:
print(list2array[2:4])
print(list2array[2:])

[3 4]
[3 4]


In [47]:
print(list2array[1:3])

[2 3]


Let's say you were curious what the final value in the array was. Maybe you are looking at distances to stars and you want to know what the last one recorded was.

You can use negative indices to look at the ends of arrays.

In [48]:
print(list2array[-1])

4


Similarly, you can use negative indices to look at chunks (slices) of the arrays. Say you wanted the last two itmes of an array:

In [49]:
print(list2array[-2:])

[3 4]


We can also save slices of arrays for later use.

In [50]:
array_end = list2array[-2:]
print(array_end)

[3 4]


Now let's say that we want to look at distances to stars and we want to find the furthest one. We will use arbitrary units. The important thing to consider here is that a higher number is a larger distance.

In [51]:
star_dist = np.random.rand(10)
print(star_dist)

[0.74905795 0.89305903 0.22546555 0.09990591 0.36284305 0.50387986
 0.0284737  0.90326022 0.4986233  0.51672618]


There are a few ways to determine the furthest point. It might be helpful for later to have the stars in order of distance. We can easily sort the array to put it in order of increasing distance.

In [52]:
sorted_distance = np.sort(star_dist)
print(sorted_distance)
print(sorted_distance[-1])
print("Furthest star distance = " + str(sorted_distance[-1]))

[0.0284737  0.09990591 0.22546555 0.36284305 0.4986233  0.50387986
 0.51672618 0.74905795 0.89305903 0.90326022]
0.9032602184414807
Furthest star distance = 0.9032602184414807


There is a more direct method if we are just interested in the largest distance, however.

In [53]:
print(np.max(star_dist))


0.9032602184414807


We can also use a similar method to find the smallest.

In [54]:
print(np.min(star_dist))

0.028473703533253736


We can also choose only values that meet certain criteria. Say we only wanted values that are above a distance of 0.5 (in our arbitrary units). Or values that are only below 0.5.

In [55]:
print(sorted_distance[sorted_distance > 0.5])
print(sorted_distance[sorted_distance < 0.5])
print(sorted_distance[(sorted_distance > 0.5) & (sorted_distance < 0.75)])

[0.50387986 0.51672618 0.74905795 0.89305903 0.90326022]
[0.0284737  0.09990591 0.22546555 0.36284305 0.4986233 ]
[0.50387986 0.51672618 0.74905795]


It is important to use "&" instead of "and" when doing multiple conditions as we showed above. It is also important to put each condition in parentheses. Ex (sorted_distance > 0.5)

In [56]:
indices = np.where(sorted_distance > 0.5)
print(np.where(sorted_distance > 0.5))

(array([5, 6, 7, 8, 9]),)


In [57]:
sorted_distance[indices]

array([0.50387986, 0.51672618, 0.74905795, 0.89305903, 0.90326022])

You can also have multidimensional arrays. There are many uses for them and they behave very similarly to one dimensional arrays. There is a slight difference in how you get information out of them, however.

In [58]:
array3d = np.random.rand(4,3)
print(array3d)

[[0.50750333 0.84763999 0.45341537]
 [0.51567438 0.26297856 0.47710429]
 [0.42896082 0.05033666 0.83717323]
 [0.4813966  0.9543646  0.2742225 ]]


Let's say these are cartesian coordinates for four stars. The first column is the x values, the second column is the y values, and the third column is the z values. The way we get the information out is a bit different.

In [59]:
print("The first index gets us: " + str(array3d[0]))

The first index gets us: [0.50750333 0.84763999 0.45341537]


In [60]:
print(array3d[0][0])

0.5075033260528284


In [61]:
print("The first column (the x positions) is: " + str(array3d[:,0]))

The first column (the x positions) is: [0.50750333 0.51567438 0.42896082 0.4813966 ]


You can tell a multidimensional array to get the first column by using ":,". [:,0] will get the first column, [:,1] will get the second, and so on.

From that point, the array acts in the same way as we have shown before.

In [62]:
print("The x position of the first star is: " + str(array3d[:,0][0]))

The x position of the first star is: 0.5075033260528284


Arrays are also incredibly useful when doing math. As I mentioned at the beginning, you can't multiply a list by a number. Math operations do work on arrays, however.

If you multiply an array by a number, it will multiply each value in the array by that number. The same is true for any other math operation.

In [63]:
print(list2array)
print(list2array * 2)
print(list2array - 10)
print(list2array + 3)
print(list2array / 4)
print(list2array ** 2)
print(np.sqrt(list2array))

[1 2 3 4]
[2 4 6 8]
[-9 -8 -7 -6]
[4 5 6 7]
[0.25 0.5  0.75 1.  ]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


Let's say we want to take our cartesian coordiantes (XYZ) and turn them into a single distance (R).

We can use a simple function to do this for future use too. Arrays can be fed into a function the same way a single number could be.

In [64]:
def radius(xyz):
    x = xyz[:,0]
    y = xyz[:,1]
    z = xyz[:,2]

    r = np.sqrt(x ** 2 + y ** 2 + z ** 2)

    return(r)

In [65]:
print(array3d)

[[0.50750333 0.84763999 0.45341537]
 [0.51567438 0.26297856 0.47710429]
 [0.42896082 0.05033666 0.83717323]
 [0.4813966  0.9543646  0.2742225 ]]


In [66]:
r_dist = radius(array3d)
print(r_dist)

print(np.sort(r_dist))

[1.08703205 0.75013751 0.9420192  1.10351821]
[0.75013751 0.9420192  1.08703205 1.10351821]


Finally, we can edit arrays. If we know how many points we need before starting a process, we can make an array of 0s with the length of the number of points we will have.

For example, if we had 10 stars that we were going to analyze with a function to get their brightness, we could make an array of 0s with 10 spots.

In [67]:
array0 = np.zeros(10)
print(array0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


We can then input values into the array once we have them. For now, let's just put in values 0 through 9 into the array using a loop.

In [68]:
for i in range(len(array0)):
    print(i)
    array0[i] = i
print(array0)

0
1
2
3
4
5
6
7
8
9
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


The same is true for a multidimensional array. If we need a 2D array, we use () and input the size of the array there.

In [69]:
array0_2d = np.zeros((2,3))
print(array0_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [70]:
array0_2d[0][2] = 3
array0_2d[1][0] = 1
print(array0_2d)

[[0. 0. 3.]
 [1. 0. 0.]]


In [86]:
print(array3d[0])
r_arr = np.zeros(len(array3d))
mass = np.asarray([0.5, 1, 1.5, 2])
print(r_arr)
r = []
r_small = []
m_small = []
for i in range(len(array3d)):
  r_temp = np.sqrt(array3d[i][0] ** 2 + array3d[i][1] **2 + array3d[i][2] ** 2)
  if r_temp < 1:
    r_small.append(r_temp)
    m_small.append(mass[i])
  r.append(r_temp)



[0.50750333 0.84763999 0.45341537]
[0. 0. 0. 0.]


In [97]:
print(array3d)
print(array3d[:,0])
r = np.sqrt(array3d[:,0] ** 2 + array3d[:,1] ** 2 + array3d[:,2] ** 2)
print(r)

[[0.50750333 0.84763999 0.45341537]
 [0.51567438 0.26297856 0.47710429]
 [0.42896082 0.05033666 0.83717323]
 [0.4813966  0.9543646  0.2742225 ]]
[0.50750333 0.51567438 0.42896082 0.4813966 ]
[1.08703205 0.75013751 0.9420192  1.10351821]


In [102]:
r_small_ind = np.where((r<1) & (mass == 1))
print(r[r_small_ind])
print(mass[r_small_ind])

[0.75013751]
[1.]


In [74]:
values = np.loadtxt('/snap.dat.0001')

ValueError: the number of columns changed from 8 to 6 at row 28150; use `usecols` to select a subset and avoid this error

In [ ]:
print(values)

In [ ]:
FG = values[values[:,0] > 50000]
SG = values[values[:,0] <= 50000]

In [ ]:
xyz_FG = FG[:,2:5]
xyz_SG = SG[:,2:5]

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
fig, ax = plt.subplots(figsize = (7,7))
ax.set_xlim(-50,50)
ax.set_ylim(-50,50)
ax.plot(xyz_FG[:,0], xyz_FG[:,2], 'o')
ax.plot(xyz_SG[:,0], xyz_SG[:,2], 'o')

In [103]:
def rad(x, y, z):
  r = np.sqrt(x ** 2 + y ** 2 + z ** 2)
  return(r)




In [104]:
rad(2, 5,7)

8.831760866327848

In [105]:
rad(array3d[:,0], array3d[:,1], array3d[:,2])

array([1.08703205, 0.75013751, 0.9420192 , 1.10351821])